version: '3.1'

services:
  app:
    image: 'c2f260194837'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=user
      - DB_PASS=pass
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass